### ISSUE TITLE
Enable test

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/vcard4android#13]
This test
https://github.com/bitfireAT/vcard4android/blob/3e2bacdbda5bafe3a3be5c97d5ed89f2185330a0/src/androidTest/java/at/bitfire/vcard4android/contactrow/EventBuilderTest.kt#L41-L55

Was commented until https://github.com/mangstadt/ez-vcard/issues/113 is merged, which now it is. I don't know in which version it was fixed, so maybe we have to wait until #11 is closed.

**Comment by rfc2822** [comment]
Can we take enable this test in #11? It would belong there because "Update library to version XXX" PRs should also contain ncessary/related code changes.

**Comment by ArnyminerZ** [comment]
Added in 05a521c9f3115e6ebeed687131bd3ac535097cba
