### ISSUE TITLE
test suite fails on Windows

### ISSUE THREAD

**Issue by mbiebl** [bitfireAT/vcard4android#18]
Running `./gradlew check` on Windows results in
```
> Task :vcard4android:testDebugUnitTest

at.bitfire.vcard4android.ContactTest > testVCard3FieldsAsVCard3 FAILED
    org.junit.ComparisonFailure at ContactTest.kt:161

121 tests completed, 1 failed

> Task :vcard4android:testDebugUnitTest FAILED

> Task :vcard4android:testReleaseUnitTest FAILED

at.bitfire.vcard4android.ContactTest > testVCard3FieldsAsVCard3 FAILED
    org.junit.ComparisonFailure at ContactTest.kt:161

121 tests completed, 1 failed
```

Appears to be a CR LF issue

**Comment by rfc2822** [comment]
Can you please also provide a PR? :) No Windows here to test.

**Comment by ArnyminerZ** [comment]
Can reproduce, I'll take a look and open a PR

**Comment by ArnyminerZ** [comment]
Logs:
```
Jun 21, 2023 7:35:38 PM at.bitfire.vcard4android.ContactWriter validate
WARNING: vCard validation warnings

expected:<...o 1715 EST, Mon-Fri.[

]
Second note> but was:<...o 1715 EST, Mon-Fri.[

]
Second note>
```

**Comment by ArnyminerZ** [comment]
Replacing
https://github.com/bitfireAT/vcard4android/blob/c2f201ae62e01f59b8d7b08ffc8fc47ab83c041a/lib/src/test/java/at/bitfire/vcard4android/ContactTest.kt#L161
with 
```kotlin
assertEquals("This fax number is operational 0800 to 1715 EST, Mon-Fri.\r\n\r\n\r\nSecond note", c.note)
```
fixes the issue, but obviously breaks the linux build 😅

**Comment by mbiebl** [comment]
I guess something like this could work:
```
-        assertEquals("This fax number is operational 0800 to 1715 EST, Mon-Fri.\n\n\nSecond note", c.note)
+        assertEquals(String.format("This fax number is operational 0800 to 1715 EST, Mon-Fri.%n%n%nSecond note"), c.note)
```
Then again, I don't know if `c.note` is supposed to contain platform specific line feeds i.e. I don't know if  there is a genuine bug here or just if simply the test needs to be updated.

**Comment by ArnyminerZ** [comment]
@rfc2822 which approach do you prefer? See #19 also

**Comment by rfc2822** [comment]
Have commented in #19. Are there other affected places or is the one from the PR the only affected line?

**Comment by ArnyminerZ** [comment]
Yup, both `check` and `connectedCheck` passes correctly 👍🏼
