### ISSUE TITLE
Broken EPIPE in PhotoBuilder

### ISSUE THREAD

**Issue by terix2k12** [bitfireAT/vcard4android#34]
Hi, I am running into an exception while syncing contacts with Davx5.

As a result the sync fails `Soft error (max retries reached)` and a lot of contacts are actually missing. 
Probaly just the faulty Contactimage should be skipped, but other data and other contacts should still be synced?

Not sure if this issue should rather be put into the davx5 repo...

The StackTrace leads me to the Photobuilder.kt from reading the source it looks like it should throw an ContactsStorageException. But the uncaught/unchecked IO exception seems to prevent that.

Here is the StackTrace:

```
--- BEGIN DEBUG INFO ---
SYNCHRONIZATION INFO Account: Account {name=......), type=at.bitfire.davdroid.address_book} Authority: com.android.contacts EXCEPTION
 java.io.IOException: write failed: EPIPE (Broken pipe) at libcore.io.IoBridge.write(IoBridge.java:651) at
 java.io.FileOutputStream.write(FileOutputStream.java:406) at java.io.FileOutputStream.write(FileOutputStream.java:384) at 
at.bitfire.vcard4android.contactrow.PhotoBuilder$Companion.insertPhoto(PhotoBuilder.kt:146) at 
at.bitfire.vcard4android.AndroidContact.update(AndroidContact.kt:138) at 
at.bitfire.davdroid.resource.LocalContact.update(LocalContact.kt:3) at 
at.bitfire.davdroid.syncadapter.ContactsSyncManager$processCard$1.invoke(ContactsSyncManager.kt:14) at 
at.bitfire.davdroid.syncadapter.ContactsSyncManager$processCard$1.invoke(ContactsSyncManager.kt:1) at 
at.bitfire.davdroid.syncadapter.SyncManager.localExceptionContext(SyncManager.kt:8) at 
at.bitfire.davdroid.syncadapter.ContactsSyncManager.processCard(ContactsSyncManager.kt:88) at 
at.bitfire.davdroid.syncadapter.ContactsSyncManager.access$processCard(ContactsSyncManager.kt:1) at 
at.bitfire.davdroid.syncadapter.ContactsSyncManager$downloadRemote$1$1$1.invoke(ContactsSyncManager.kt:10) at 
at.bitfire.davdroid.syncadapter.ContactsSyncManager$downloadRemote$1$1$1.invoke(ContactsSyncManager.kt:1) at 
at.bitfire.davdroid.syncadapter.SyncManager.responseExceptionContext(SyncManager.kt:13) at 
at.bitfire.davdroid.syncadapter.ContactsSyncManager$downloadRemote$1.invoke$lambda$0(ContactsSyncManager.kt:22) at 
at.bitfire.davdroid.syncadapter.ContactsSyncManager$downloadRemote$1.$r8$lambda$aTmx16DT01n3ZmMyYWepKV6Txjc(ContactsSyncManager.kt:1) at at.bitfire.davdroid.syncadapter.ContactsSyncManager$downloadRemote$1$$ExternalSyntheticLambda0.onResponse(R8$$SyntheticClass:3) at at.bitfire.dav4jvm.Response$Companion.parse(Response.kt:307) at at.bitfire.dav4jvm.DavResource.processMultiStatus$parseMultiStatus(DavResource.kt:51) at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:16) at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:9) at at.bitfire.dav4jvm.DavAddressBook.multiget(DavAddressBook.kt:69) at at.bitfire.davdroid.syncadapter.ContactsSyncManager$downloadRemote$1.invoke(ContactsSyncManager.kt:10) at at.bitfire.davdroid.syncadapter.ContactsSyncManager$downloadRemote$1.invoke(ContactsSyncManager.kt:1) at at.bitfire.davdroid.syncadapter.SyncManager.remoteExceptionContext(SyncManager.kt:1) at at.bitfire.davdroid.syncadapter.SyncManager.remoteExceptionContext(SyncManager.kt:5) at at.bitfire.davdroid.syncadapter.ContactsSyncManager.downloadRemote(ContactsSyncManager.kt:46) at at.bitfire.davdroid.syncadapter.SyncManager$syncRemote$1$download$1.invokeSuspend(SyncManager.kt:14) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:112) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:163) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:103) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:3) at at.bitfire.davdroid.syncadapter.SyncManager.syncRemote(SyncManager.kt:39) at at.bitfire.davdroid.syncadapter.SyncManager$performSync$1.invoke(SyncManager.kt:29) at at.bitfire.davdroid.syncadapter.SyncManager$performSync$1.invoke(SyncManager.kt:1) at at.bitfire.davdroid.syncadapter.SyncManager.unwrapExceptions(SyncManager.kt:2) at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.kt:20) at at.bitfire.davdroid.syncadapter.ContactSyncer.sync(ContactSyncer.kt:218) at at.bitfire.davdroid.syncadapter.Syncer.onPerformSync(Syncer.kt:119) at at.bitfire.davdroid.syncadapter.SyncWorker$doWork$2$1$1.invoke(SyncWorker.kt:4) at at.bitfire.davdroid.syncadapter.SyncWorker$doWork$2$1$1.invoke(SyncWorker.kt:1) at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:59) at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt:13) at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:5) at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:41) at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:9) at at.bitfire.davdroid.syncadapter.SyncWorker$doWork$2.invokeSuspend(SyncWorker.kt:503) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:112) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012) Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe) at libcore.io.Linux.writeBytes(Native Method) at libcore.io.Linux.write(Linux.java:296) at libcore.io.ForwardingOs.write(ForwardingOs.java:943) at libcore.io.BlockGuardOs.write(BlockGuardOs.java:448) at libcore.io.ForwardingOs.write(ForwardingOs.java:943) at libcore.io.IoBridge.write(IoBridge.java:646) ... 52 

 Locale(s): [en_US] Time zone: Europe/Berlin
```

 4.3.12.1-ose
Android version: 14 (UQ1A.240105.002) Device: Google Pixel 6a (bluejay)

 but happens also also on older versions and other phones

**Comment by rfc2822** [comment]
Looks like this belongs here to vcard4android.

I think it should be ignored when the photo can't be inserted because of an I/O error (or a ContactsStorageException should be thrown).

Do you maybe have the original vCard?

**Comment by terix2k12** [comment]
Previous vCard is downloaded with Firefox from Nextcloud, if I forward the vCard from my Android devide it is like this

```
BEGIN:VCARD
VERSION:2.1
N:Mustermann;Erika;;;
FN:Erika Mustermann
TEL;HOME:+4915112345678
EMAIL;WORK:person@email.de
ORG:organisation GmbH
PHOTO;ENCODING=BASE64;JPEG:/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEU
 AAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAA
..........
 FA+SZJPn00cyNaeKBkLou0cMdwIJ49PNr8ajpSTyoiBvDAj0luOOAcTwhe90Nq58z6QaHq6qY
 z1NRkdDNLK5uXZqdCWP3JJOBjUPBnndTqDw3aHqqp98qUklMD/BDNJEg/0xqPywMAy6YUvD//
 2Q==

END:VCARD
```

**Comment by rfc2822** [comment]
Thanks for the info, we will try to reproduce and/or make it so that the photo doesn't break sync.

@sunkup Can you please have a look and try to reproduce it and find a better way of handling the exception?

**Comment by sunkup** [comment]
> Since it contains personal information I obviously have to remove most of the vCard

Fair, but without the original image I am unsure how to reproduce this in a timely manner. Or does one of you have some leads I could try?  ( also asking @rfc2822 )

> I think it should be ignored when the photo can't be inserted because of an I/O error (or a ContactsStorageException should be thrown).

If we catch the IOException and ignore it a ContactsStorageException will be thrown. We can of course throw the ContactsStorageException earlier, but it would be thrown in any case. 

> Should still not break sync for all other contacts imho.

A ContactsStorageException will, be [handled as a hard sync error (databaseError)](https://github.com/bitfireAT/davx5/blob/03ebd5beeab2436ff8dca0a3e18f67544e5ed208/app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncManager.kt#L755-L758), which are [not retried](https://github.com/bitfireAT/davx5/blob/03ebd5beeab2436ff8dca0a3e18f67544e5ed208/app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncWorker.kt#L418-L423). So the remaining contacts would still not be synced.

If this is to be addressed, it should be a separate issue in DAVx5 then: 
Because retrying with soft errors does not seem to help save the photo, we would have to ignore (only log) the thrown ContactsStorageExceptions and maybe tell the user that this contact is problematic, without making the exception into a soft or hard sync error.

**Comment by terix2k12** [comment]
Maybe you can just manually throw the `android.system.ErrnoException` as in the StackTrace?

If you provide me a more private channel I could provide you with the full vCard.

I'll try to get more information inbetween via ADB or maybe compiling the App myself, it has been quite some time though since I worked with Android 😅

**Comment by sunkup** [comment]
> Maybe you can just manually throw the `android.system.ErrnoException` as in the StackTrace?

Yes. And I could also throw the IOException, but then we would not learn why the Android Contact Storage rejects certain images.

> If you provide me a more private channel I could provide you with the full vCard.

You are very welcome to send it via our support page: https://www.davx5.com/support/
Otherwise you may send it to support@davx5.com
 
> I'll try to get more information inbetween via ADB or maybe compiling the App myself, it has been quite some time though since I worked with Android 😅

I don't think that'd be necessary, since it's not really an issue with DAVx5 as far as I can see?

**Comment by devvv4ever** [comment]
Didn't receive any ticket regarding this yes. @terix2k12 please mention the thread here if you send it!

**Comment by rfc2822** [comment]
> A ContactsStorageException will, be [handled as a hard sync error (databaseError)](https://github.com/bitfireAT/davx5/blob/03ebd5beeab2436ff8dca0a3e18f67544e5ed208/app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncManager.kt#L755-L758), which are [not retried](https://github.com/bitfireAT/davx5/blob/03ebd5beeab2436ff8dca0a3e18f67544e5ed208/app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncWorker.kt#L418-L423). So the remaining contacts would still not be synced.

Yes, ContactsStorageException is designed as hard error.

In the current case, I'm voting for ignoring the I/O error when the photo can't be inserted and just log a warning. It may be that Android doesn't understand the photo and this shouldn't prevent synchronization of the contact.

**Comment by sunkup** [comment]
> In the current case, I'm voting for ignoring the I/O error when the photo can't be inserted and just log a warning. It may be that Android doesn't understand the photo and this shouldn't prevent synchronization of the contact.
>
> So basically we just need a try/catch around
> 
> https://github.com/bitfireAT/vcard4android/blob/fcabcf205beec27cafac87bda1804091554cd269/lib/src/main/java/at/bitfire/vcard4android/contactrow/PhotoBuilder.kt#L62-L66
> 
> and log a warning when an (IO?)Exception arrives.

`openAssetFile` does not throw an IOException, but `FileNotFoundException` and `RemoteException`, so a try/catch around 

https://github.com/bitfireAT/vcard4android/blob/fcabcf205beec27cafac87bda1804091554cd269/lib/src/main/java/at/bitfire/vcard4android/contactrow/PhotoBuilder.kt#L63-L65

would suffice.

In any case, doing only this will not prevent the `ContactsStorageException` from being thrown a few lines later (`photoUri` will be `null`):

https://github.com/bitfireAT/vcard4android/blob/fcabcf205beec27cafac87bda1804091554cd269/lib/src/main/java/at/bitfire/vcard4android/contactrow/PhotoBuilder.kt#L92-L95  

We'd have to log the failed photo save here too, instead of throwing the exception.

**Comment by terix2k12** [comment]
@devvv4ever I'd like to speak with the person first, if she will agree to send the image.

My gut feeling is rather, that it is not a problem with the vCard itself. Since the method signature receives a ByteArray, I guess the array breaks somewhere higher in the call stack. -> Still trying to reproduce locally and collect more information. Will come back to you then.

The ContactsStorageException is not even thrown in the first place, right? Because the Exception prevents the code from reaching the `(photoUri != null)` check you cited.

I can't tell which behavior the ContactSotrageExcetion will have, so this PR looks good to me, since it improves the exception handling in `PhotoBuilder.kt` It just leaves the photo on Contact as null but will probaly continue syncing the remaining contacts.
