### ISSUE TITLE
[FEATURE] package as apk similar to ICSx⁵

### ISSUE THREAD

**Issue by mister-monster** [bitfireAT/vcard4android#43]
I'm using ICSx⁵ to keep my system calendar up to date from a ics file, and I'd like to do the same with my contacts. VCFx⁵ perhaps?

**Comment by rfc2822** [comment]
Not planned… you try to set up a read-only CardDAV server, maybe copy the .vcf to some server that supports to serve from a file (there should be some). Or write a minimal SabreDAV backend…
