### ISSUE TITLE
Support IS_READ_ONLY for Data and Group rows

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/vcard4android#8]
Currently, we have [support for the RAW_CONTACT_IS_READ_ONLY flag](https://github.com/bitfireAT/vcard4android/blob/581eac4117634bf59eba14b69acb8bb1cce95d2a/src/main/java/at/bitfire/vcard4android/AndroidContact.kt#L191).

However Contacts apps can still change the data rows of read-only contacts (and quite everything is a data row, for instance the name). So for native contacts read-only support, we need

- [x] IS_READ_ONLY support for Data rows (like we [had it before](https://github.com/bitfireAT/vcard4android/blob/4e5acd17221491006014affb33cb5f41b8b84ed9/src/main/java/at/bitfire/vcard4android/AndroidContact.kt#L762-L763) the rewrite to data row builders)
- [x] GROUP_IS_READ_ONLY support for AndroidGroup
- [x] Tests

**Comment by sunkup** [comment]
atm tests are still missing due to https://github.com/bitfireAT/davx5/issues/151
